# app server configuration:
server:
  port: 8000
  compression:
    enabled: true
  tomcat:
    uri-encoding: UTF-8
  error:
    include-stacktrace: never

  # netty:
  #  idle-timeout: 5000
  #  connection-timeout: 6000
  servlet:
    context-path: /admin-console/v1

# app spring configuration:
spring:
  application:
    name: admin-console

  # webflux:
  #  base-path: /admin-console/v1
  banner:
    location: 'classpath:/banner.txt'
  main:
    banner-mode: log
    lazy-initialization: false
  mvc:
    converters:
      preferred-json-mapper: jsonb
  devtools:
    restart:
      enabled: true
    add-properties: false
  # kafka configuration:
  kafka:
    consumer:
      bootstrap-servers: localhost:29092

  # rabbitmq configuration:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: bacsystem
    publisher-returns: true
    publisher-confirm-type: correlated


  # redis configuration:
  data:
    redis:
      host: localhost
      port: 6379
      password: redis
# app logging configuration:
logging:
  level:
    com.bacsystem: info
    root: info
    web: info
    sql: debug
    kafka: info

# app swagger configuration
springdoc:
  api-docs:
    enabled: true


# app health configuration:
management:
  info:
    git:
      enabled: true
      mode: full
  endpoint:
    health:
      probes:
        enabled: true
  health:
    db:
      enabled: true
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true


microservices:
  consumer: true
  cron: "0 */59 * * * *"